### PR TITLE
Additional page sizes

### PR DESCRIPTION
**Pull request by lmingle**
Added/Updated page sizes based upon Appendix B Table B.1 of the Adobe PostScript Printer Description File Format Specification version 4.3.

### CODE REVIEW

**Comment by MarcinZiabek** [comment]
@lmingle Thank you very much for your pull request. According to our short email conversation, I allowed myself to continue it here. I hope, you are ok with that.

Making the long story short. I am assuming that the vast majority of generated documents are using common and standardized page sizes. In fact, 99.9% of documents created in Europe are using the A4 size. Including the rest of available sizes specified by ISO is already feeling wrong. 

You have accurately noticed that in the United States, another set of formats is commonly used. I do not consider including every existing format in the library (apparently there are way too many standards) as the right choice. However, whatever is really commonly used, should be included. @lmingle, can you please try to limit the number of page size to a list as short as possible? Whatever you consider essential. Everybody who wants to use an exotic size surely knows its dimensions. 

---

There is another topic with page orientation. From a library standpoint, making a distinction does not make much sense probably. After all, it is all about flipping dimensions. The SkiaSharp library seems to NOT make any distinction in this regard as well. If I am right, we may want to prepare a small extension method to flip width and height in the Size class, so it is easy to use any Size in landscape orientation.

```c#
PageSize.A4; // portrait
PageSize.A4.Rotated(); // landscape

public static Size Rotated(this Size size)
{
    return new Size(size.Height, size.Width);
}
```

Can you please investigate if it makes sense? We have two naming conventions to choose from: portrait/landscape and vertical/horizontal. Or just call it rotated as in the example. It would be better if the name makes also sense outside of the page size topic (extension method is available everywhere).

**Comment by MarcinZiabek** [comment]
It may also make sense to revise if existing sizes correspond to real dimensions. Initially, the library supported only integer units which turned to be insufficient. Not sure if a fraction of the point impacts anybody but if we can, it would be great to be exact (to some extent, e.g. 1/100th of the point).

**Comment by lmingle** [comment]
Rotated() would be a simple approach. Portrait() and Landscape() could then use Rotated() to modify the orientation if different from the current orientation.
```
public class Size
{
    public enum PageOrientation
    {
        Portrait,
        Landscape
    }
    public PageOrientation Orientation => (Width / Height)<= 1 ? PageOrientation.Portrait : PageOrientation.Landscape;
}
```
```
    public static class SizeExtension
    {
        public static Size Rotated(this Size size) => new Size(size.Height, size.Width);

        public static Size Portrait(this Size size) => size.Orientation == Size.PageOrientation.Portrait ? size : size.Rotated();

        public static Size Landscape(this Size size) => size.Orientation == Size.PageOrientation.Landscape ? size : size.Rotated();
    }
```

Looking at papersizes.io the values of each page size is shown as points rounded to 1/10th which seems exact enough.

**Comment by MarcinZiabek** [comment]
**This is very good thinking!** However, we need to be careful about the Size class, as it is used extensively in many places in the library. To make it safer, let's create a subclass. As it derives from Size, it does not impact anything.

```c#
public class PageSize : Size
{

}
```

I was thinking about PageOrientation. I am not sure if anybody would be interested in the particular state of such property. After all, we want to design a very simple flow of picking the right document size, not a management system. What do you think about making the code even simpler?

```c#
public static PageSize Portrait(this PageSize size)
{
    Width = Math.Min(size.Width, size.Height),
    Height = Math.Max(size.Width, size.Height)
}

public static PageSize Landscape(this PageSize size)
{
    Width = Math.Max(size.Width, size.Height),
    Height = Math.Min(size.Width, size.Height)
}
```

This way, we don't need to worry about page orientation, rotation or any other additional method. And the usage is quite nice (the same as in your case):

```c#
PageSize.A4.Landscape()
```

I know it is nitpicking. However, right now, my plan is to slowly clean the library from anything that looks prototype-ish and to make it mature. The more people use the library, the harder it is to change your mind, hence trying to be careful. I think we are really close to include this change in 2021.04 ❤

**Comment by lmingle** [comment]
I agree with a simple clean API. My initial instinct is that the class naming should include 'orientation' since it conveys the purpose. How do you feel about using SizeOrientation or shortening it to just be Orientation?
```
    public class SizeOrientation : Size
    {
        public SizeOrientation(float width, float height) : base(width, height)
        { }
    }

    public static class SizeOrientationExtensions
    {
        public static SizeOrientation Portrait(this Size size)
        {
            return new SizeOrientation(Math.Min(size.Width, size.Height), Math.Max(size.Width, size.Height));
        }

        public static SizeOrientation Landscape(this Size size)
        {
            return new SizeOrientation(Math.Max(size.Width, size.Height), Math.Min(size.Width, size.Height));
        }
    }
```

**Comment by MarcinZiabek** [comment]
Good question. Personally, I would say that the only and single purpose of such class (or data type to be specific) is to describe the size of the page. Orientation seems to be connected to the ratio between width and height, which is essentially a side product, the way we perceive the page. Therefore, I would prefer to call such class "PageSize" which clearly describes its purpose.

So, just making a small suggestion regarding your code:
```c#
public class PageSize: Size
{
    public PageSize(float width, float height) : base(width, height)
    { 

    }
}

public static class PageSizes
{
    // list every size, e.g.
    public static PageSize A4 => new PageSize(595, 842);
    // more...

    public static PageSize Portrait(this PageSize size)
    {
        return new PageSize(
            width: Math.Min(size.Width, size.Height), 
            height: Math.Max(size.Width, size.Height));
    }

    public static PageSize Landscape(this PageSize size)
    {
        return new PageSize(
            width: Math.Max(size.Width, size.Height), 
            height: Math.Min(size.Width, size.Height));
    }
}
```
From this stage, I think it is good enough to include in the 2021.04. Can you please make those last small adjustments?

**Comment by MarcinZiabek** [comment]
@lmingle I have accepted this pull request, it is planned to be publicly available in version 2021.04. Thank you for your help and patience, great work!

**Pull request merged**
